Repository OZ-Coding-School/oz_react_mini_11, pull requests merged in 2025-06, with the labels that each got.

#11 [mission1] 1단계 미션 구현 - 최시영/4팀
  .gitignore
  README.md
  eslint.config.js
  index.html
  package-lock.json
  package.json
  public/vite.svg
  src/App.css
  src/App.jsx
  src/assets/react.svg
  src/components/Layout.jsx
  src/components/MovieCard.jsx
  src/components/MovieSlide.jsx
  src/components/NavBar.jsx
  src/data/movieDetailData.json
  src/data/movieListData.json
  src/index.css
  src/main.jsx
  src/pages/MovieDetail.jsx
  src/pages/MovieList.jsx
  vite.config.js
Labels: mission-1

#6 [mission1] 1단계 미션 구현 - 김은빈/5팀
  .gitignore
  README.md
  eslint.config.js
  index.html
  package-lock.json
  package.json
  postcss.config.js
  public/vite.svg
  src/App.jsx
  src/App.scss
  src/assets/react.svg
  src/component/Detail.jsx
  src/component/Layout.jsx
  src/component/Main.jsx
  src/component/MovieCard.jsx
  src/component/NavBar.jsx
  src/data/movieDetailData.json
  src/data/movieListData.json
  src/index.css
  src/main.jsx
  tailwind.config.js
  vite.config.js
Labels: mission-1

#18 [mission1] 1단계 미션 구현 - 함서연/2팀
  .gitignore
  README.md
  eslint.config.js
  index.html
  package-lock.json
  package.json
  src/App.jsx
  src/assets/ChevronLeft.jsx
  src/assets/ChevronRight.jsx
  src/components/MovieCard.jsx
  src/components/TopMoviesSlider/TopMovieCard.jsx
  src/components/TopMoviesSlider/TopMoviesSlider.jsx
  src/constants/imageBaseUrl.js
  src/data/movieDetailData.json
  src/data/movieListData.json
  src/hooks/useFetch.js
  src/hooks/useSliderDrag.js
  src/hooks/useThrottle.js
  src/index.css
  src/layout/Layout.jsx
  src/layout/NavBar.jsx
  src/main.jsx
  src/pages/MovieCardsList.jsx
  src/pages/MovieDetail.jsx
  src/utils/getTopRatedMovies.js
  vite.config.js
Labels: mission-1

#21 [mission1] 1단계 미션 구현 - 김희영/1팀
  .gitignore
  README.md
  eslint.config.js
  index.html
  package-lock.json
  package.json
  public/vite.svg
  src/App.css
  src/App.jsx
  src/Layout.jsx
  src/MovieCard.jsx
  src/MovieDetail.jsx
  src/Navbar.jsx
  src/assets/react.svg
  src/index.css
  src/main.jsx
  src/movieDetailData.json
  src/movieListData.json
  vite.config.js
Labels: mission-1

#15 [Mission 1] 1단계 미션 구현 - 박재민/1팀
  .gitignore
  README.md
  eslint.config.js
  index.html
  package-lock.json
  package.json
  public/vite.svg
  src/App.css
  src/App.jsx
  src/assets/HomeLogo.png
  src/assets/react.svg
  src/components/HighRatedSwiper.jsx
  src/components/movie/MovieCard.jsx
  src/components/movie/MovieDetail.jsx
  src/components/movie/StarRating.jsx
  src/components/nav/Layout.jsx
  src/components/nav/NavBar.jsx
  src/data/movieDetailData.json
  src/data/movieListData.json
  src/index.css
  src/main.jsx
  src/pages/Home.jsx
  vite.config.js
Labels: mission-1

#22 [mission1] 1단계 미션 구현 - 김승원/1팀
  .github/pull_request_template.md
  .gitignore
  .prettierignore
  .prettierrc
  README.md
  eslint.config.js
  index.html
  package-lock.json
  package.json
  src/App.css
  src/App.jsx
  src/components/Layout.jsx
  src/components/MovieCard.jsx
  src/components/MovieDetail.jsx
  src/components/NavBar.jsx
  src/data/movieDetailData.json
  src/data/movieListData.json
  src/index.css
  src/main.jsx
  vite.config.js
Labels: mission-1

#8 [mission1] 1단계 미션 구현 - 백서영 / 3팀
  .github/pull_request_template.md
  .gitignore
  README.md
  eslint.config.js
  index.html
  package-lock.json
  package.json
  public/vite.svg
  src/App.css
  src/App.jsx
  src/assets/react.svg
  src/components/MovieCard.jsx
  src/components/MovieDetail.jsx
  src/components/NavBar.jsx
  src/data/movieDetailData.json
  src/data/movieListData.json
  src/images/angle-left.svg
  src/images/angle-right.svg
  src/index.css
  src/layout/Layout.jsx
  src/main.jsx
  src/pages/Home.jsx
  src/styles/GlobalStyles.jsx
  src/styles/theme.js
  vite.config.js
Labels: mission-1

#13 [mission1] 1단계 미션 구현 - 이재건 / 3팀
  .gitignore
  README.md
  eslint.config.js
  index.html
  mission1_data/__MACOSX/data/._movieDetailData.json
  package-lock.json
  package.json
  postcss.config.js
  public/movieDetailData.json
  public/movieListData.json
  public/vite.svg
  src/App.css
  src/App.jsx
  src/assets/react.svg
  src/component/layout/Layout.jsx
  src/component/moviecard/MovieCard.jsx
  src/component/moviedetail/MovieDetail.jsx
  src/component/moviegrid/MovieGrid.jsx
  src/component/movielist/MovieList.jsx
  src/component/navbar/NavBar.jsx
  src/component/slider/MovieCylinder.jsx
  src/index.css
  src/main.jsx
  tailwind.config.js
  vite.config.js
Labels: mission-1

#19 [mission1] 1단계 미션 구현 - 장혜진/3팀
  my-app/.gitignore
  my-app/README.md
  my-app/eslint.config.js
  my-app/index.html
  my-app/package-lock.json
  my-app/package.json
  my-app/public/vite.svg
  my-app/src/App.css
  my-app/src/App.jsx
  my-app/src/Layout.jsx
  my-app/src/assets/data/movieDetailData.json
  my-app/src/assets/data/movieListData.json
  my-app/src/assets/react.svg
  my-app/src/components/MovieCard.jsx
  my-app/src/components/NavBar.jsx
  my-app/src/components/Navbar.css
  my-app/src/constants/image.js
  my-app/src/index.css
  my-app/src/main.jsx
  my-app/src/pages/Home.css
  my-app/src/pages/Home.jsx
  my-app/src/pages/MovieDetail.css
  my-app/src/pages/MovieDetail.jsx
  my-app/vite.config.js
Labels: mission-1

#16 [mission1] 1단계 미션 구현 - 박주영/6팀
  .gitignore
  .prettierignore
  .prettierrc
  README.md
  eslint.config.js
  index.html
  package-lock.json
  package.json
  postcss.config.js
  public/data/movieDetailData.json
  public/data/movieListData.json
  public/vite.svg
  src/App.css
  src/App.jsx
  src/components/Layout.jsx
  src/components/MovieCard.jsx
  src/components/MovieList.jsx
  src/components/MovieSlide.jsx
  src/index.css
  src/main.jsx
  src/pages/Home.jsx
  src/pages/MovieDetail.jsx
  src/pages/NavBar.jsx
  tailwind.config.js
  vite.config.js
Labels: mission-1

#40 [mission1] 1단계 미션 구현 - 조윤아/6팀
  .gitignore
  README.md
  data/movieDetailData.json
  data/movieListData.json
  eslint.config.js
  index.html
  package-lock.json
  package.json
  public/vite.svg
  src/App.css
  src/App.jsx
  src/assets/react.svg
  src/component/NavBar.css
  src/component/NavBar.jsx
  src/index.css
  src/main.jsx
  src/page/Main.css
  src/page/Main.jsx
  src/page/MovieDetail.css
  src/page/MovieDetail.jsx
  vite.config.js
Labels: mission-1

#33 [mission2] 2단계 미션 구현 - 김민창 / 2팀
  .gitignore
  CallToken.js
  src/App.jsx
  src/MovieList.jsx
  src/component/MovieCard.jsx
  src/component/MovieDetail.jsx
  src/component/MovieSlider.jsx
  src/component/SkeletonCard.jsx
  src/movieDetailData.json
  src/movieListData.json
Labels: mission-2

#34 [mission2] 2단계 미션 구현 - 정동준/2팀
  .gitignore
  README.md
  eslint.config.js
  index.html
  package-lock.json
  package.json
  postcss.config.js
  public/vite.svg
  src/App.css
  src/App.jsx
  src/assets/movieDetailData.json
  src/assets/movieListData.json
  src/assets/react.svg
  src/components/Layout.jsx
  src/components/MovieCard.jsx
  src/components/MovieDetail.jsx
  src/components/NavBar.jsx
  src/index.css
  src/main.jsx
  tailwind.config.js
  vite.config.js
Labels: mission-2

#47 [Mission 1] 1단계 미션 구현 - 박준규/5팀
  .gitignore
  README.md
  eslint.config.js
  index.html
  package-lock.json
  package.json
  public/vite.svg
  src/App.css
  src/App.jsx
  src/assets/react.svg
  src/components/Layout.jsx
  src/components/MovieCard.jsx
  src/components/NavBar.jsx
  src/components/Swiper.jsx
  src/data/movieDetailData.json
  src/data/movieListData.json
  src/img/img01.jpg
  src/index.css
  src/main.jsx
  src/pages/Login.jsx
  src/pages/Main.jsx
  src/pages/MovieDetail.jsx
  src/pages/Signup.jsx
  vite.config.js
Labels: mission-1

#36 [Mission 2] 2단계 미션 구현 - 이재은 / 1팀
  .gitignore
  src/DB/movieDetailData.json
  src/DB/movieListData.json
  src/pages/Detail.jsx
  src/pages/MovieCard.jsx
Labels: mission-2

#42 [Mission 2] 2단계 미션 구현 - 김태현/4팀
  .gitignore
  package-lock.json
  package.json
  src/App.jsx
  src/components/Layout.jsx
  src/components/MovieCard.jsx
  src/components/MovieDetail.jsx
  src/components/MovieList.jsx
  src/components/MovieSlider.css
  src/components/MovieSlider.jsx
  src/components/NavBar.jsx
  src/constans.js
  src/index.css
  src/main.jsx
Labels: mission-2

#43 [mission2] 2단계 미션 구현 - 최시영 / 4팀
  .gitignore
  src/App.css
  src/App.jsx
  src/components/MovieCard.jsx
  src/components/MovieSlide.jsx
  src/constants.js
  src/pages/MovieDetail.jsx
  src/pages/MovieList.jsx
  src/utils/getImageUrl.js
Labels: mission-2

#44 [mission2] 2단계 미션 구현 - 이재현/4팀
  .gitignore
  package-lock.json
  package.json
  src/App.tsx
  src/components/MovieCard.tsx
  src/components/Navbar.tsx
  src/components/lodaing/Loading.tsx
  src/constants.ts
  src/main.tsx
  src/page/Details.tsx
  src/page/Home.tsx
  src/utils/axiosUtils.ts
Labels: mission-2

#46 [Mission 2] 2단계 미션 구현 - 김희영/1팀
  .gitignore
  package-lock.json
  package.json
  src/App.css
  src/api/movieApi.js
  src/components/MovieCard.jsx
  src/components/Navbar.jsx
  src/components/SkeletonMovieCard.jsx
  src/index.css
  src/main.jsx
  src/pages/App.jsx
  src/pages/Layout.jsx
  src/pages/MovieDetail.jsx
  tailwind.config.js
Labels: mission-2

#49 [mission2] 2단계 미션 구현 - 이명우/6팀
  .gitignore
  src/api/movie.js
  src/components/MovieDetail/MovieBackdrop.jsx
  src/components/MovieDetail/MovieCompanies.jsx
  src/components/MovieDetail/MovieGenres.jsx
  src/components/MovieDetail/MovieMeta.jsx
  src/components/MovieDetail/MovieOverview.jsx
  src/components/MovieDetail/MoviePoster.jsx
  src/components/MovieDetail/index.jsx
Labels: mission-2

#50 [mission2] 2단계 미션 구현 - 조윤아/6팀
  .gitignore
  src/App.jsx
  src/page/Main.css
  src/page/Main.jsx
  src/page/MovieDetail.jsx
Labels: mission-2

#56 [mission2] 2단계 미션 구현- 박준규/5팀
  .gitignore
  src/App.jsx
  src/components/Layout.jsx
  src/components/MainBanner.jsx
  src/components/MovieCard.jsx
  src/components/SubTitle.jsx
  src/data/movieDetailData.json
  src/data/movieListData.json
  src/main.jsx
  src/pages/MovieDetail.jsx
Labels: mission-2

#54 [mission2] 2단계 미션 구현 - 백서영/3팀
  .gitignore
  package-lock.json
  package.json
  public/vite.svg
  src/App.css
  src/App.jsx
  src/App.styles.jsx
  src/apis/movieDetailApi.js
  src/apis/popularMovieApi.js
  src/assets/animations/loading-animation.json
  src/assets/animations/menu-animation.json
  src/assets/images/angle-left.svg
  src/assets/images/angle-right.svg
  src/assets/react.svg
  src/components/MovieCard/MovieCard.jsx
  src/components/MovieCard/MovieCard.styles.jsx
  src/components/MovieCard/MovieCardSkeleton.jsx
  src/components/MovieDetail/MovieDetail.jsx
  src/components/MovieDetail/MovieDetail.styles.jsx
  src/components/MovieDetail/MovieDetailSkeleton.jsx
  src/components/NavBar/NavBar.jsx
  src/components/NavBar/NavBar.styles.jsx
  src/data/movieDetailData.json
  src/data/movieListData.json
  src/index.css
  src/layout/Layout.jsx
  src/layout/Layout.styles.jsx
  src/pages/Home/Home.jsx
  src/pages/Home/Home.styles.jsx
Labels: mission-2

#58 [mission2] 2단계 미션 구현 - 김현중/3팀
  oz_react_mini_11/.gitignore
  oz_react_mini_11/public/movieListData.json
  oz_react_mini_11/src/App.css
  oz_react_mini_11/src/App.jsx
  oz_react_mini_11/src/components/MovieCard.jsx
  oz_react_mini_11/src/components/NavBar.jsx
  oz_react_mini_11/src/pages/Home.jsx
  oz_react_mini_11/src/pages/MovieDetail.jsx
Labels: mission-2

#48 [mission2] 2단계 미션 구현 - 이재건/3팀
  .gitignore
  package-lock.json
  package.json
  src/component/moviedetail/MovieDetail.jsx
  src/component/movielist/MovieList.jsx
  src/component/slider/MovieCylinder.jsx
Labels: mission-2

#57 [mission1] 1단계 미션 구현 - 박권영
  .gitignore
  README.md
  eslint.config.js
  index.html
  package-lock.json
  package.json
  public/vite.svg
  src/App.css
  src/App.jsx
  src/assets/react.svg
  src/data/movieDetailData.json
  src/data/movieListData.json
  src/index.css
  src/main.jsx
  src/page/Layout.jsx
  src/page/MovieCard.jsx
  src/page/MovieDetail.jsx
  src/page/MoviePanda.css
  src/page/MoviePanda.jsx
  src/page/NavBar.css
  src/page/NavBar.jsx
  vite.config.js
Labels: mission-1

#55 [mission3] 3단계 미션 구현 - 김은빈/5팀
  index.html
  src/App.jsx
  src/App.scss
  src/component/Detail.jsx
  src/component/Join.jsx
  src/component/Login.jsx
  src/component/Main.jsx
  src/component/MovieCard.jsx
  src/component/NavBar.jsx
  src/component/Search.jsx
  src/constant/constant.js
  src/hooks/useDebounce.jsx
  src/index.css
Labels: mission-3

#60 [Mission3] 3단계 미션 구현 - 김민창/2팀
  src/App.jsx
  src/MovieList.jsx
  src/SearchResult.jsx
  src/component/Layout.jsx
  src/component/MovieCard.jsx
  src/component/MovieDetail.jsx
  src/component/MovieSlider.jsx
  src/component/NavBar.jsx
  src/component/RatingBar.jsx
  src/component/SearchBar.jsx
  src/constant/constant.js
  src/hooks/useDebounce.js
  src/hooks/useDetailMovie.js
  src/hooks/useMovies.js
  src/hooks/useSearchMovies.js
  src/index.css
  src/main.jsx
Labels: mission-3

#62 [mission3] 3단계 미션 구현 - 함서연/2팀
  package-lock.json
  package.json
  src/App.jsx
  src/assets/Dark.jsx
  src/assets/Light.jsx
  src/components/MovieCard.jsx
  src/components/TopMoviesSlider/TopMovieCard.jsx
  src/components/TopMoviesSlider/TopMoviesSlider.jsx
  src/components/skeletons/MovieCardSkeleton.jsx
  src/components/skeletons/MovieDetailSkeleton.jsx
  src/components/skeletons/TopMovieCardSkeleton.jsx
  src/constants/tmdbUrl.js
  src/data/dummies/movieDetailData.json
  src/data/dummies/movieListData.json
  src/hooks/useDebounce.js
  src/index.css
  src/layout/NavBar.jsx
  src/pages/MovieCardsList.jsx
  src/pages/MovieDetail.jsx
  src/pages/SearchResults.jsx
  src/utils/getSearchURL.js
  src/utils/toggleTheme.js
Labels: mission-3

#67 Mission 3] 3단계 미션 구현 - 김태현/4팀
  package-lock.json
  package.json
  src/App.css
  src/App.jsx
  src/components/Layout.jsx
  src/components/MovieCard.css
  src/components/MovieCard.jsx
  src/components/MovieDetail.css
  src/components/MovieDetail.jsx
  src/components/MovieList.jsx
  src/components/MovieSlider.css
  src/components/MovieSlider.jsx
  src/components/NavBar.css
  src/components/NavBar.jsx
  src/components/SearchResult.jsx
  src/components/SkeltonCard.jsx
  src/constants.js
  src/hooks/useDebounce.js
  src/hooks/useSearchMovies.js
  src/index.css
  vite.config.js
Labels: mission-3

#69 [mission3] 3단계 미션 구현 - 최시영/4팀
  src/App.jsx
  src/components/MovieCard.jsx
  src/components/NavBar.jsx
  src/constants.js
  src/hooks/useDebounce.js
  src/pages/MovieDetail.jsx
  src/pages/MovieList.jsx
  src/pages/SearchResult.jsx
  src/utils/apiUrls.js
  src/utils/getImageUrl.js
Labels: mission-3

#72 [ mission3 ] 3단계 미션 구현 - 박준규/5팀
  postcss.config.js
  src/App.css
  src/App.jsx
  src/components/Debounce.jsx
  src/components/Footer.jsx
  src/components/Layout.jsx
  src/components/MainBanner.jsx
  src/components/MovieCard.jsx
  src/components/NavBar.jsx
  src/components/SearchPage.jsx
  src/components/SubTitle.jsx
  src/components/Swiper.jsx
  src/index.css
  src/main.jsx
  src/pages/Main.jsx
  src/pages/MovieDetail.jsx
  tailwind.config.js
Labels: mission-3

#65 [Mission 3] 3단계 미션 구현 - 이재은 / 1팀
  src/App.css
  src/Components/NavBar.jsx
  src/hooks/useDebounce.jsx
  src/pages/Detail.jsx
  src/pages/MovieCard.jsx
Labels: mission-3

#35 [Mission 2] 2단계 미션 구현 - 박재민/1팀
  .gitignore
  package-lock.json
  package.json
  src/App.jsx
  src/api/TMDM_api.js
  src/components/HighRatedSwiper.jsx
  src/components/movie/MovieCard.jsx
  src/components/movie/MovieDetail.jsx
  src/pages/Home.jsx
Labels: mission-2

#73 [mission3] 3단계 미션 구현 - 김승원/1팀
  README.md
  src/components/Index.jsx
  src/components/MovieCard.jsx
  src/components/MovieDetail.jsx
  src/components/NavBar.jsx
  src/components/SearchButton.jsx
  src/data/ApiInfo.jsx
  src/hooks/useDebounce.jsx
  src/hooks/useFetch.jsx
Labels: mission-3

#81 [Mission4] 4단계 미션 구현 - 김민창/2팀
  .vite/deps/_metadata.json
  .vite/deps/package.json
  package-lock.json
  package.json
  src/App.jsx
  src/component/FormInput.jsx
  src/component/MovieSlider.jsx
  src/component/NavBar.jsx
  src/component/SearchBar.jsx
  src/hooks/supabase.js
  src/hooks/useDebounce.js
  src/pages/Login.jsx
  src/pages/Singup.jsx
Labels: mission-4

#83 [Mission 4] 4단계 미션 구현 - 김태현/4팀
  package-lock.json
  package.json
  src/App.jsx
  src/assets/google_login.png
  src/assets/kakao_login.png
  src/components/CommonInput.jsx
  src/components/InputField.jsx
  src/components/MovieCard.jsx
  src/components/MovieDetail.jsx
  src/components/MovieList.jsx
  src/components/MovieSlider.jsx
  src/components/NavBar.jsx
  src/components/SearchResult.jsx
  src/components/SocialLoginButtons.jsx
  src/constants.js
  src/contexts/AuthContext.jsx
  src/hooks/useSearchMovies.js
  src/hooks/useSupabaseAuth.js
  src/lib/supabase.js
  src/main.jsx
  src/pages/Login.jsx
  src/pages/Signup.jsx
Labels: mission-4

#84 [mission4] 4단계 미션 구현 - 최시영/4팀
  index.html
  public/images/MoviePoster.jpg
  public/images/cinema-chairs.jpg
  public/images/profile.png
  src/App.jsx
  src/components/FormInput.jsx
  src/components/MovieCard.jsx
  src/components/MovieSlide.jsx
  src/components/NavBar.jsx
  src/main.jsx
  src/pages/Login.jsx
  src/pages/MovieDetail.jsx
  src/pages/MovieList.jsx
  src/pages/SearchResult.jsx
  src/pages/Signup.jsx
  src/supabase/auth/index.js
  src/supabase/auth/useAuth.js
  src/supabase/auth/useEmail.auth.js
  src/supabase/auth/useOauth.auth.js
  src/supabase/context/index.jsx
  src/supabase/index.js
  src/supabase/utilities/config.js
  src/supabase/utilities/dto.js
  src/supabase/utilities/env.js
  src/supabase/utilities/index.js
  src/supabase/utilities/localStorage.js
Labels: mission-4

#89 [mission5] 5단계 미션 구현 - 이명우/6팀
  src/App.jsx
  src/api/withlist.js
  src/components/GoogleLoginButton.jsx
  src/components/MovieCard.jsx
  src/components/MovieDetail/MovieBackdrop.jsx
  src/components/MovieDetail/index.jsx
  src/components/Nav/NavBar.jsx
  src/components/RequireAuth.jsx
  src/context/AuthContext.js
  src/context/AuthContext.jsx
  src/pages/AuthCallbackPage.jsx
  src/pages/MyPage.jsx
  src/pages/SignupPage.jsx
Labels: mission-5

#90 [mission5] 5단계 미션 구현 - 함서연/2팀
  src/App.jsx
  src/components/MovieCard.jsx
  src/components/MyPageComponents/BookmarkSection.jsx
  src/components/MyPageComponents/ProfileSection.jsx
  src/components/NavBar.jsx
  src/contexts/isLoginContext.jsx
  src/main.jsx
  src/pages/LogIn.jsx
  src/pages/MovieCardsList.jsx
  src/pages/MovieDetail.jsx
  src/pages/MyPage.jsx
  src/pages/OAuthCallback.jsx
  src/pages/OAuthKakaoCallback.jsx
  src/pages/SearchResults.jsx
  src/pages/SignUp.jsx
  src/supabase/auth/useAuth.js
  src/supabase/auth/useEmail.auth.js
  src/supabase/context/index.jsx
  src/supabase/utilities/dto.js
  src/utils/bookmarkAPI.js
Labels: mission-5

#85 [mission4] 4단계 미션 구현 - 정동근/5팀
  package-lock.json
  package.json
  src/App.jsx
  src/api/auth.js
  src/components/LoginForm.jsx
  src/components/NavBar.jsx
  src/components/SignupForm.jsx
  src/components/UserMenu.jsx
  src/lib/supabase.js
  src/pages/Login.jsx
  src/pages/Signup.jsx
Labels: mission-4

#87 [mission4] 4단계 미션 구현 - 김은빈/5팀
  package-lock.json
  package.json
  src/App.jsx
  src/App.scss
  src/component/Input.jsx
  src/component/Join.jsx
  src/component/Login.jsx
  src/component/NavBar.jsx
  src/component/SignUp.jsx
  src/constant/supabaseClient.js
  src/contexts/UserContext.jsx
  src/utils/authUtils.js
Labels: mission-4

#96 Mission free
  src/App.scss
  src/components/Login.jsx
  src/components/MyFavorite.jsx
  src/components/MyPage.jsx
  src/components/MyProfile.jsx
  src/components/MyReview.jsx
  src/components/NavBar.jsx
Labels: mission-free
